services:
  db:
    image: postgres:17
    container_name: digin_postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - digin_kompetanse_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    container_name: digin_app
    build:
      context: .
      target: dev            
    working_dir: /app
    env_file: .env
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      DOTNET_USE_POLLING_FILE_WATCHER: ${DOTNET_USE_POLLING_FILE_WATCHER}
      DOTNET_WATCH_RESTART_ON_RUDE_EDIT: ${DOTNET_WATCH_RESTART_ON_RUDE_EDIT}
  
      
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5068:8080"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: digin_app_bin
        target: /app/bin
      - type: volume
        source: digin_app_obj
        target: /app/obj
      - type: volume
        source: digin_keys
        target: /keys
    command: ["dotnet","watch","run","--no-launch-profile","--urls","http://0.0.0.0:8080"]

volumes:
  digin_kompetanse_pgdata:
    name: digin_kompetanse_pgdata
  digin_app_bin:
  digin_app_obj:
  digin_keys:
